import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { Bank } from '../types/bank';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    textAlign: 'center',
  },
  title: {
    fontSize: 16,
    marginBottom: 10,
  },
  bankSection: {
    marginBottom: 20,
    borderBottom: '1px solid #ccc',
    paddingBottom: 10,
  },
  bankName: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  bankDetails: {
    marginLeft: 10,
    marginBottom: 5,
  },
  label: {
    fontWeight: 'bold',
  },
  footer: {
    marginTop: 20,
    borderTop: '1px solid black',
    paddingTop: 10,
    textAlign: 'center',
  }
});

interface BankListPDFProps {
  banks: Bank[];
  date?: string;
}

export const BankListPDF = ({ banks, date = new Date().toLocaleDateString() }: BankListPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Bank Branch Details Report</Text>
        <Text>Generated on: {date}</Text>
      </View>

      {banks.map((bank, ) => (
        <View key={bank.id} style={styles.bankSection}>
          <Text style={styles.bankName}>{bank.bankName} - {bank.branchName}</Text>
          <View style={styles.bankDetails}>
            <Text><Text style={styles.label}>UFI:</Text> {bank.ufi}</Text>
            <Text><Text style={styles.label}>IFSC Code:</Text> {bank.ifscCode}</Text>
            <Text><Text style={styles.label}>Address:</Text> {bank.address}</Text>
            {bank.updateAddress && (
              <Text><Text style={styles.label}>Updated Address:</Text> {bank.updateAddress}</Text>
            )}
            {bank.updatedBranchName && (
              <Text><Text style={styles.label}>Updated Branch Name:</Text> {bank.updatedBranchName}</Text>
            )}
            {bank.phoneNumber && (
              <Text><Text style={styles.label}>Phone Number:</Text> {bank.phoneNumber}</Text>
            )}
            {bank.response && (
              <Text><Text style={styles.label}>Response Type:</Text> {bank.response}</Text>
            )}
            {bank.remarks && (
              <Text><Text style={styles.label}>Remarks:</Text> {bank.remarks}</Text>
            )}
          </View>
        </View>
      ))}

      <View style={styles.footer}>
        <Text>Generated by Lepton Software Export and Research (P) Ltd.</Text>
        <Text>570, Udyog Vihar, Phase-V, Gurugram, Haryana – 122016</Text>
        <Text>http://www.leptonsoftware.com</Text>
      </View>
    </Page>
  </Document>
); 